# File name: Dockerfile
FROM rayproject/ray:2.9.0-py39-cpu

RUN pip install -U azure-cli-core==2.29.1 azure-identity==1.7.0 azure-mgmt-compute==23.1.0 azure-mgmt-network==19.0.0 azure-mgmt-resource==20.0.0 msrestazure==0.6.4 
RUN pip install -U 'pydantic<2'